{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "anthembcbs.serviceAccountName" . }}
  labels:
{{ include "anthembcbs.labels" . | indent 4 }}
{{- end -}}
